CREATE TABLE [dbo].[Cbo]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Codigo] VARCHAR(50) NOT NULL, 
    [Descricao] NVARCHAR(250) NOT NULL
)

INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1401, '2231.01', 'Médico Acupunturista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1402, '2231.02', 'Médico Alergista / Imunologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1403, '2231.03', 'Médico Anatomopatologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1404, '2231.04', 'Médico Anestesista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1405, '2231.05', 'Médico Angiologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1406, '2231.A1', 'Médico Broncoesofalogista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1407, '2231.45', 'Médico Cancerologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1408, '2231.06', 'Médico Cardiologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1409, '2231.07', 'Médico Cirurgião Cardiovascular')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1410, '2231.10', 'Médico Cirurgião de Mão')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1411, '2231.08', 'Médico Cirurgião de Cabeça e Pescoço')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1412, '2231.09', 'Médico Cirurgião do Aparelho Digestivo')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1413, '2231.11', 'Médico Cirurgião Pediátrico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1414, '2231.12', 'Médico Cirurgião Plástico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1415, '2231.13', 'Médico Cirurgião Torácico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1416, '2231.07', 'Médico Cirurgião Vascular')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1417, '2231.10', 'Médico Cirurgião, em geral')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1418, '2231.14', 'Médico Citopatologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1419, '2231.46', 'Médico de medicina esportiva')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1420, '2231.50', 'Médico de Perícias Médicas')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1421, '2231.16', 'Médico de Saúde da Família')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1422, '2231.17', 'Médico Dermatologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1423, '2231.18', 'Médico do Trabalho')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1424, '2231.25', 'Médico Endocrinologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1425, '2231.20', 'Médico Endoscopista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1426, '2231.26', 'Médico Fisiatra')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1427, '2231.28', 'Médico Gastroenterologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1428, '2231.30', 'Médico Geneticista Clínico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1429, '2231.56', 'Médico Geral Comunitário')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1430, '2231.31', 'Médico Geriatra')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1431, '2231.32', 'Médico Ginecologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1432, '2231.32', 'Médico Ginecologista / Obstétra')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1433, '2231.A2', 'Médico Hansenologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1434, '2231.33', 'Médico Hematologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1435, '2231.35', 'Médico Homeopata')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1436, '2231.34', 'Médico Hemoterapeuta')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1437, '2231.36', 'Médico Infectologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1438, '2231.22', 'Médico Intensivista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1439, '2231.37', 'Médico Legista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1440, '2231.38', 'Médico Mastologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1441, '2231.39', 'Médico Nefrologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1442, '2231.40', 'Médico Neurocirurgião')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1443, '2231.42', 'Médico Neurologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1444, '2231.23', 'Médico Nuclear')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1445, '2231.32', 'Médico Obstétra')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1446, '2231.44', 'Médico Oftamologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1447, '2231.45', 'Médico Oncologista Cirúrgico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1448, '2231.45', 'Médico Oncologista Clínico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1449, '2231.45', 'Médico Oncologista Pediátrico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1450, '2231.46', 'Médico Ortopedista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1451, '2231.47', 'Médico Otorrinolaringologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1452, '2231.48', 'Médico Patologista Clínico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1453, '2231.49', 'Médico Pediatra')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1454, '2231.15', 'Médico Plantonista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1455, '2231.51', 'Médico Pneumotisiologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1456, '2231.52', 'Médico Proctologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1457, '2231.53', 'Médico Psiquiatrico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1458, '2231.24', 'Médico Radiologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1459, '2231.54', 'Médico Radioterapeuta')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1460, '2231.55', 'Médico Reumatologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1461, '2231.56', 'Médico Sanitarista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1462, '2231.24', 'Médico Ultrasonografista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1463, '2231.57', 'Médigo Urologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1464, '2231.15', 'Médico em Geral (Clínico Geral)')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1465, '2231.15', 'Outros Médicos')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1466, '3221.05', 'Acupunturista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1467, '2516.05', 'Assistente Social, em geral')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1468, '2230.15', 'Bacteriologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1469, '2211.05', 'Biomédico (Biologista em geral)')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1470, '2234.10', 'Bioquímico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1471, '2232.12', 'Cirurgião Dentista (Endodontia)')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1472, '2232.44', 'Cirurgião Dentista (Patologia Bucal)')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1473, '2232.36', 'Cirurgião Dentista (Pediatria)')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1474, '2232.48', 'Cirurgião Dentista (Periodontia)')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1475, '2232.56', 'Cirurgião Dentista (Prótese)')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1476, '2232.60', 'Cirurgião Dentista (Radiologia)')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1477, '2232.72', 'Cirurgião Dentista (Saúde Pública)')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1478, '2232.68', 'Cirurgião Dentista (Traumatologia Buco Maxilo Faci')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1479, '2232.40', 'Cirurgião Dentista (Ortodontia)')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1480, '2232.08', 'Cirurgião Dentista, em geral')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1481, '2235.C2', 'Enfermeiro do PACS')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1482, '2235.C1', 'Enfermeiro do PSF')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1483, '2235.25', 'Enfermeiro de Terapia Intensiva')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1484, '2235.20', 'Enfermeiro de Centro Cirúrgico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1485, '2235.30', 'Enfermeiro do Trabalho')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1486, '2235.05', 'Enfermeiro, em geral')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1487, '2235.45', 'Enfermeiro Obstetra')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1488, '2235.50', 'Enfermeiro Psiquiátrico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1489, '2235.55', 'Enfermeiro Puericultor e Pediátrico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1490, '2235.60', 'Enfermeiro Sanitarista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1491, '2234.05', 'Farmacêutico, em Geral')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1492, '2234.05', 'Farmacologista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1493, '2131.55', 'Físico Nuclear')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1494, '2236.05', 'Fisioterapeuta')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1495, '2231.27', 'Foniatra')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1496, '2238.10', 'Fonoaudiólogo')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1497, '2233.05', 'Médico Veterinário, em geral')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1498, '2237.10', 'Nutricionista, em geral')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1499, '2236.15', 'Ortoptista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1500, '3223.05', 'Ótico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1501, '2230.15', 'Outros Bacteriologistas e Trabalhadores Assemelhad')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1502, '2394.15', 'Pedagogo')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1503, '2515.10', 'Psicólogo, em geral')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1504, '2236.20', 'Tc em Orientação e Mobilidade de Cegos e Deficien.')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1505, '2236.20', 'Terapeuta Ocupacional')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1506, '2236.20', 'Terapeutas em Geral')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1507, '2233.10', 'Zootecnista')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1508, '1999.A2', 'Outros profissionais Nivel Superior')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1509, '4110.05', 'Agente Administrativo')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1510, '5151.05', 'Agente Comunitário')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1511, '3522.10', 'Agente de Sanamento')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1512, '3522.10', 'Agente de Vigilancia Sanitaria')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1513, '4110.05', 'Auxiliar Administrativo')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1514, '5151.10', 'Atendente de Enfermagem')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1515, '3242.10', 'Auxiliar de Análises Clínicas')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1516, '3222.30', 'Auxiliar de Enfermagem')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1517, '3222.E2', 'Auxiliar de Enfermagem do PSF')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1518, '5151.20', 'Fiscal Sanitário')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1519, '5151.20', 'Guarda de Endemias/Agente de Zoonoses/Agente Vetor')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1520, '3241.10', 'Operador de Eletrocardiógrafo')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1521, '3241.05', 'Operador de Eletroencefalógrafo')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1522, '3241.15', 'Operador de Raios-X')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1523, '3241.15', 'Outros Operadores de Equipamentos Médicos e Odonto')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1524, '5151.15', 'Pediatria')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1525, '3221.15', 'Quiropata')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1526, '3222.05', 'Socorrista habilitado')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1527, '4110.10', 'Técnico Administrativo')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1528, '3222.10', 'Técnico de Enfermagem de Terapia Intensiva')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1529, '3222.E1', 'Técnico de Enfermagem do PSF')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1530, '3222.15', 'Técnico de Enfermagem do Trabalho')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1531, '3222.20', 'Técnico de Enfermagem Psiquiátrica')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1532, '3222.05', 'Técnico de Enfermagem, em geral')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1533, '3224.05', 'Técnico de Higiene Dental')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1534, '3225.05', 'Técnico de Ortopedia')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1535, '3241.15', 'Técnico de Radiologia')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1536, '3522.10', 'Técnico de Saneamento')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1537, '3135.D2', 'Técnico em Equipamento Médico Hospitalar')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1538, '3242.05', 'Técnico em Laboratório')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1539, '3135.D1', 'Técnico em Reabilitação')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1540, '3522.10', 'Técnico em Vigilância Sanitária')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1541, '5151.H1', 'Outros profissionais de nível técnico e médio')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1545, '2231-F3', 'Médico Cirurgião Vascular')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1546, '3222-B3', 'Socorrista habilitado')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1547, '2231-F4', 'Médico Cancerologista Pediátrico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1548, '2231-F5', 'Médico Cancerologista Cirurgico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1549, '2231-F6', 'Médico Cancerologista Clínico')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1550, '2231-F7', 'Médico em Medicina de Família e comunidade')
INSERT INTO [dbo].[Cbo] ([Id], [Codigo], [Descricao]) VALUES (1551, '2231-F8', 'Médico em Medicina Preventiva e Social')
